[WIP] Implement SFU engine
membraneframework/membrane_demo pull request #115
Opened 2021-06-15 16:44 UTC by mickel8

2021-06-29 10:51 UTC, FelonEkonom commented on webrtc/videoroom/lib/sfu/media_event.ex
> +      if length(Map.keys(event)) != 2 or length(Map.keys(event["data"])) != 2 do
JS valid object, that will be put under "data" key, may contain up to 4 fields

```js
interface RTCIceCandidateInit {
    candidate?: string;
    sdpMLineIndex?: number | null;
    sdpMid?: string | null;
    usernameFragment?: string | null;
}
```

2021-06-29 12:21 UTC, FelonEkonom commented on webrtc/videoroom/lib/videoroom_web/room_channel.ex
> +defmodule VideoRoomWeb.PeerChannel do
Rename also file

2021-06-29 12:25 UTC, FelonEkonom commented on webrtc/videoroom/lib/videoroom/room.ex
> +  end
Will it work, if `to` will be equal to `:broadcast`?

2021-06-29 12:29 UTC, FelonEkonom commented on webrtc/videoroom/lib/videoroom_web/room_channel.ex
> +      [] -> Membrane.Room.start(name: {:via, Registry, {Membrane.Room.Registry, room_id}})
This is incompatible with how we name channel of screensharing peer (see `getChannelId` function, declared in `utils.ts` and used in `room.ts`)

2021-06-29 12:33 UTC, FelonEkonom commented on webrtc/videoroom/lib/sfu/sfu.ex
> +  end
I would consider deleting this function, in my opinion using it makes code less readable

2021-06-29 12:40 UTC, FelonEkonom commented on webrtc/videoroom/lib/sfu/media_event.ex
> +    |> then(fn event -> {:media_event, to, event} end)
`Room` expects from first element of returned tuple to be `:sfu_media_event` instead of `:media event`

2021-06-29 12:49 UTC, FelonEkonom commented on webrtc/videoroom/test/sfu/sfu_test.exs
> +  end
```suggestion
defp generate_key(), do: UUID.uuid4()
```

2021-07-02 12:13 UTC, mat-hek requested changes

2021-07-06 09:12 UTC, mickel8 commented
The API definition has been moved to membraneframework/membrane_sfu#2

2021-07-13 13:46 UTC, mickel8 commented on webrtc/videoroom/assets/src/room_ui.ts
>  interface State {
I simplified this file a lot so I am not sure if this makes sense to convert it to the class. I did it with `room.ts`

2021-07-15 15:44 UTC, mat-hek approved these changes

2021-07-15 15:44 UTC, mat-hek commented on webrtc/videoroom/lib/videoroom/room.ex
> +defmodule Membrane.Room do
```suggestion
defmodule Videoroom.Room do
```

2021-07-15 15:44 UTC, mat-hek commented on webrtc/videoroom/lib/videoroom/room.ex
> +        vad: false
this should be default

2021-07-19 14:54 UTC, mat-hek approved these changes

2021-07-19 14:54 UTC, mat-hek commented on webrtc/videoroom/assets/src/room.ts
> +        onJoinError: (data) => {
```suggestion
        onJoinError: (metadata) => {
```

2021-07-20 14:29 UTC, mat-hek approved these changes

2021-07-20 14:32 UTC, merged