Add benchmarks
membraneframework/membrane_demo pull request #166
Opened 2021-11-29 11:18 UTC by mickel8

closes membraneframework/membrane_rtc_engine#35

2021-12-21 10:06 UTC, Qizot requested changes

2021-12-21 10:06 UTC, Qizot commented on webrtc/videoroom_advanced/benchmarks/simple.exs
> +    if browsers >= 1 do
I would raise here to avoid one nesting.

2021-12-21 10:06 UTC, Qizot commented on webrtc/videoroom_advanced/benchmarks/results/testrtc_multiroom.txt
> +================
Isn't this the same file as the one for `testrtc_simple`?

2021-12-23 10:17 UTC, mickel8 commented on webrtc/videoroom_advanced/benchmarks/multiroom.exs
> +Beamchmark.run(MultiroomScenario,
Yes, in other case this wouldn't make any sense

2021-12-23 13:22 UTC, Qizot approved these changes

2021-12-23 13:37 UTC, merged