Cleaned up configs and updated README.md
membraneframework/membrane_demo pull request #42
Opened 2021-03-12 13:50 UTC by Qizot

2021-03-16 09:28 UTC, mat-hek approved these changes

2021-03-16 10:06 UTC, mat-hek requested changes

2021-03-16 10:06 UTC, mat-hek commented on webrtc/videoroom/README.md
maybe add a sentence or two on what does it do

2021-03-16 10:31 UTC, Qizot commented on webrtc/videoroom/config/runtime.exs
> +  ]
I tried to simplify it right now. I don't know if I can take it any futher as there are not mandatory env variables for prod environment.

2021-03-17 10:29 UTC, mat-hek commented on webrtc/videoroom/config/runtime.exs
> +  ]
```elixir
def get_env(env, default) do
  if config_env() == :prod do
    System.fetch_env!(env)
  else
    System.get_env(env, default)
  end
end
```

2021-03-17 11:26 UTC, mat-hek approved these changes

2021-03-17 11:27 UTC, merged