msid in tracks
membraneframework/membrane_demo pull request #77
Opened 2021-04-27 14:07 UTC by FelonEkonom

Adjusting code to related changes in membrane_webrtc_plugin

2021-04-29 06:31 UTC, Qizot requested changes

2021-04-29 06:31 UTC, Qizot commented on webrtc/videoroom/assets/src/membraneWebRTC.ts
> +  ids: string[];
Probably should be trackIds. `ids` does not tell much what it is.

2021-04-29 06:31 UTC, Qizot commented on webrtc/videoroom/assets/src/membraneWebRTC.ts
> +      const isScreenSharing = id.includes("SCREEN") || false;
Have you checked that screensharing works? I tried to wrap my head around this pr and one in webrtc plugin and got lost easily...

2021-04-29 12:06 UTC, mickel8 requested changes

2021-04-29 12:06 UTC, mickel8 commented on webrtc/videoroom/lib/videoroom/pipeline.ex
> +      |> Map.put(:mid_to_msid, mid_to_msid)
Why do we store this in state? I think we don't need these lines

2021-10-06 11:25 UTC, mickel8 commented
Outdated

2021-10-06 11:25 UTC, closed without merging