Show participants list
membraneframework/membrane_demo pull request #84
Opened 2021-05-07 08:14 UTC by FelonEkonom

2021-05-07 09:57 UTC, Qizot requested changes

2021-05-07 09:57 UTC, Qizot commented on webrtc/videoroom/assets/src/room_ui.ts
> +  participantsNamesList.innerHTML =
Use `innerText`. I don't know though if list of participants should be displayed in a row instead of column.

2021-05-07 10:01 UTC, mat-hek requested changes

2021-05-07 10:01 UTC, mat-hek commented on webrtc/videoroom/assets/src/membraneWebRTC.ts
> +  onOfferDataArrival?: (data: OfferData) => void;
```suggestion
  onOfferData?: (data: OfferData) => void;
```

2021-05-10 13:56 UTC, mickel8 requested changes
I would consider changing two things:
1. Put each participant in a separate row so that we would have
```
Participants:
participant1
participant2
participant3
...
```
2. Accent somehow this list e.g. by using **bold** font for **Participants** and a little larger size

2021-05-12 13:40 UTC, FelonEkonom commented
> I would consider changing two things:
> 
>     1. Put each participant in a separate row so that we would have
> 
> 
> ```
> Participants:
> participant1
> participant2
> participant3
> ...
> ```
> 
>     1. Accent somehow this list e.g. by using **bold** font for **Participants** and a little larger size

I think, that maybe it is better idea, to wait with changing look of this list to the moment, when UI developer will come to this project, because I think, that there is very big chance, that we will have to change it then, one way or another

2021-05-12 13:53 UTC, mickel8 approved these changes

2021-05-13 08:19 UTC, merged